export type App = 'QA' | 'Sales' | 'Service' | 'Travel Sales'

export type Tab =
	| 'Itineraries'
	| 'Settings'
	| 'Accounts'
	| 'Channels'
	| 'Cases'
	| 'Contacts'
	| 'Opportunities'
	| 'Leads'
	| 'Dashboards'
	| 'Reports'
	| 'Tasks'
	| 'Notes'
	| 'Files'
	| 'Home'
	| 'Chatter'
	| 'Campaigns'
	| 'Contracts'
	| 'Orders'
	| 'Products'
	| 'Assets'
	| 'Quotes'
	| 'Forecasts'
	| 'Solutions'
	| 'Knowledge'
	| 'Activities'
	| 'Calendar'
	| 'Email'
	| 'Documents'
	| 'Trips'
	| 'Services'
	| 'Packages'
	| 'Locations'
	| 'Promotions'
	| 'Currency Setup'
